# Faster key repeat and sane defaults
set -g mouse on
set -g history-limit 100000
setw -g aggressive-resize on
set -g default-terminal "screen-256color"
bind r source-file ~/.tmux.conf \; display "tmux reloaded"
